version: '3.3'

services:
  app:
    container_name: "backend"
    build: .
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - "mongo"
    command: "yarn start"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: docker

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: docker
      ME_CONFIG_MONGODB_URL: mongodb://root:docker@mongo:27017/
